export const CurrencyActionTypes = {
  GET_CURENCIES: 'GET_CURENCIES',
  CHANGE_CURENCIES: 'CHANGE_CURENCIES',
  TOGGLE_OPEN_CURRECIES: 'TOGGLE_OPEN_CURRENCY',
  CLOSE_CURRENCIES_ON_CLICK_OUT:
    'CLOSE_CURRENCIES_ON_CLICK_OUT',
};
